import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  ltop: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    zIndex: 1,
  },
  lleft: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    left: 0,
    top: 75,
    zIndex: 3,
  },
  lright: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    left: 0,
    top: 70,
    zIndex: 2,
  },
  lbottom: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    left: 26,
    top: 200,
    zIndex: 4,
  },
  rtop: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    zIndex: 1,
    right: 0,
  },
  rleft: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    top: 70,
    zIndex: 2,
  },
  rright: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    top: 75,
    zIndex: 3,
  },
  rbottom: {
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: 26,
    top: 200,
    zIndex: 4,
  },
  rightSole: {
    height: 300,
    width: 110,
  },
  leftSoles: {
    height: 300,
    width: 110,
  },
  backgroundVideo: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    right: 0,
  },
});
